<?php
return array(
    'mod' => array(
        'pf' => 'pf service',
        'area' => 'define area',
        'addr' => 'define host,define range,define subnet',
        'addrall' => 'define host,define subnet,define range,define mac',
        'host' => 'define host',
        'range' => 'define range',
        'subnet' => 'define subnet',
        'addrgroup' => 'define group_address',
        'schedule' => 'define schedule',
        'timegroup' => 'define group_schedule',
        'service' => 'define service',
        'servicegroup' => 'define group_service',
        'server' => 'define server',
        'balance' => 'define virtual_server',
        'interfaces' => 'network interfaces',
        'physics' => 'network physicalinterface',
        'macvif' => 'network macvif',
        'tagvif' => 'network tagvif',
        'vlan' => 'network vlan',
        'virtualline' => 'network virtualline',
        'virtual-line' => 'network virtual-line',
        'bond' => 'network bond',
        'veth' => 'network veth',
        'suitstate' => 'network suitstate',
        'route' => 'network route',
        'route-policy' => 'network route-policy',
        'isp_route_all' => 'network isp_route_all',
        'arp' => 'network arp',
        'neighbour' => 'network neighbour',
        'mac' => 'network mac',
        'dhcp' => 'network dhcp dhcpd_subnet',
        'dhcp_server' => 'network dhcp server',
        'dhcp_host' => 'network dhcp dhcpd_host',
        'dhcp_server_wait' => 'network dhcp_server_wait',
        'dhcp_server_start' => 'network dhcp dhcp_server_start',
        'dhcp_host' => 'network dhcp dhcpd_host',
        'dhcp_lease' => 'network dhcp dhcpd_lease',
        'dhcpv6_subnet' => 'network dhcpv6 dhcpdv6_subnet',
        'dhcpv6_server_wait' => 'network dhcp6_server_wait',
        'dhcpv6_server_start' => 'network dhcpv6 dhcpv6_server_start',
        'dhcpv6' => 'network dhcpv6 server',
        'dhcpv6_host' => 'network dhcpv6 dhcpdv6_host',
        'dhcpv6_lease' => 'network dhcpv6 dhcpdv6_lease',
        'radvd' => 'network radvd',
        'tunnel' => 'network tunnel',
        'ip_probe' => 'network ip-probe',
        'managesubnet_managehost' => 'system snmp managesubnet,system snmp managehost',
        'traphost' => 'system snmp traphost',
        'snmpv3user' => 'system snmp snmpv3user'

    ),

    'action' => array(
        'all' => 'show all',
        'd' => 'del',
        'm' => 'modify',
        'w' => 'webui-group',
        'l' => 'list',
        'cl' => 'clear',
        'di' => 'display',
        'd_subnet' => 'del_subnet',
        'c_subnet' => 'clean_subnet',
        'd_host' => 'del_host',
        'c_host' => 'clean_host',
        'dt' => 'delete'
    )
);

?>